aws_account_id = "240086272411"
aws_ami_name = "amzn2-ami-kernel-5.10-hvm*"
aws_ami_name_ubuntu = "ubuntu/images/hvm-ssd/ubuntu-jammy-*"
ec2_instance_type = "t2.micro"
key_name = "talent-academy-ec2"
